// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pojfmdxsoqfxfzkujwah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvamZtZHhzb3FmeGZ6a3Vqd2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg2MDA0ODUsImV4cCI6MjA0NDE3NjQ4NX0.8od0l7BnaDoVhh-ms5Yqw1r-08Zz2K9yhXTTFBCsuCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);